### PR TITLE
Improve reader performance

### PR DESCRIPTION
**Pull request by ksss**
# Micro benchmark:

```rb
require "language_server-protocol"

t = Time.now
reader = LanguageServer::Protocol::Transport::Stdio::Reader.new
reader.read do |request|
end
puts(Time.now - t)
```

```
$ ruby -e 'puts File.size("log.txt")'
498965

$ cat log.txt | bundle exec ruby benchmark.rb
before => 0.055778
after => 0.003873
```

------

This is micro benchmark.
In actual use, there may not be that much change.

### CODE REVIEW

**Comment by mtsmfm** [comment]
@ksss Thank you for your PR.
Can you share log.txt or the way to create that?

**Comment by ksss** [comment]
The log.txt file is in the format of the language server protocol.

```
Content-Length: *

{"method":"foo",...}Content-Length: *

{"method":"bar",...}Content-Length: *

{"method":"baz",...}Content-Length: *
...
```

The log.txt file is created by slightly modifying reader.rb.

```diff
diff --git a/lib/language_server/protocol/transport/io/reader.rb b/lib/language_server/protocol/transport/io/reader.rb
index bbd6559..4575ae9 100644
--- a/lib/language_server/protocol/transport/io/reader.rb
+++ b/lib/language_server/protocol/transport/io/reader.rb
@@ -15,11 +15,14 @@ module LanguageServer
             header_parsed = false
             content_length = nil

+            f = File.open("log.txt", "a+")
             while char = io.getc
               buffer << char

               unless header_parsed
                 if buffer[-4..-1] == "\r\n" * 2
+                  f.flock(File::LOCK_EX)
+                  f.write(buffer)
                   content_length = buffer.match(/Content-Length: (\d+)/i)[1].to_i

                   header_parsed = true
@@ -27,6 +30,8 @@ module LanguageServer
                 end
               else
                 if buffer.bytesize == content_length
+                  f.write(buffer)
+                  f.flock(File::LOCK_UN)
                   request = JSON.parse(buffer, symbolize_names: true)

                   block.call(request)
```

Then, run `$ steep check`.

**Review by mtsmfm — APPROVED** [review]

**Comment by mtsmfm** [comment]
Thanks, I'll add benchmark script later.

**Comment by mtsmfm** [comment]
I've just released 3.16.0.3

https://rubygems.org/gems/language_server-protocol/versions/3.16.0.3

**Pull request merged**
